spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: P@ssw0rd123

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: secret

  activemq:
    broker-url: ${ACTIVEMQ_BROKER_URL}
    user: ${ACTIVEMQ_USERNAME}
    password: ${ACTIVEMQ_PASSWORD}
    packages:
      trust-all: true

  mail:
    host: smtp.gmail.com #outlook.office365.com
    port: 587
    from: Sample JWTLogin APP
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        socketFactory:
          port: 587
          class: javax.net.ssl.SSLSocketFactory
          fallback: false

logging:
  level:
    org:
      springframework: WARN
      hibernate:
        SQL: WARN
        stat: WARN

active-mq:
  notification:
    user : sample.queue2

mail:
  no-reply: ${NO_REPLY_EMAIL}
  from: ${EMAIL_FROM}
  name: ${EMAIL_NAME}