spring:
  datasource :
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: P@ssw0rd123

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: secret

logging:
  level:
    org:
      springframework: WARN
      hibernate:
        SQL: WARN
        stat: WARN
